const fs=require('fs');const out='imweb-handoff';for(const d of ['common','content','assets'])fs.mkdirSync(out+'/'+d,{recursive:true});
for(const f of fs.readdirSync('shop-assets').filter(f=>/\.(jpg|png)$/.test(f)))fs.copyFileSync('shop-assets/'+f,out+'/assets/'+f);
const data={assetBase:'https://ghddbwjd20-dotcom.github.io/secret-route-website/shop-assets/',imageUrls:{},links:{'index.html':'/','shop.html':'/shop','new.html':'/new','best.html':'/best','collection.html':'/collection','support.html':'/support','shipping.html':'/shipping','about.html':'/about','terms.html':'/terms','privacy.html':'/privacy',contact:'/contact'},productUrls:{},products:JSON.parse(fs.readFileSync('shop-assets/products.json','utf8'))};
fs.writeFileSync(out+'/common/02-settings.txt','<script>\nwindow.SR_SHOP = '+JSON.stringify(data,null,2)+';\n</script>');
function scope(css){let r='',i=0;while(i<css.length){const s=css.indexOf('{',i);if(s<0){r+=css.slice(i);break}const h=css.slice(i,s);let d=1,e=s+1;for(;d&&e<css.length;e++){if(css[e]==='{')d++;if(css[e]==='}')d--}const c=css.slice(s+1,e-1);r+=h.trim().startsWith('@')?h+'{'+scope(c)+'}':h.split(',').map(x=>{x=x.trim().replace(/\bhtml\b|\bbody\b/g,'.sr-content');return x.startsWith('.sr-content')?x:'.sr-content '+x}).join(',')+'{'+c+'}';i=e}return r}
const css=scope(fs.readFileSync('shop-assets/shop.css','utf8'))+'\n.sr-content{--sr-accent:#ff781f;--sr-bg:#fff0e3;--sr-text:#2c2723;font-family:"Malgun Gothic",Arial,sans-serif;background:var(--sr-bg);color:var(--sr-text);letter-spacing:-.035em}.sr-content .button,.sr-content .filters button.active{background:var(--sr-accent)}.sr-content .button.light{background:white}.sr-content,.sr-content>section,.sr-content .page-body,.sr-content .page-intro{background-color:var(--sr-bg)!important}.sr-content .form-heading{padding:35px 0 20px}.sr-content .form-heading h2{margin:8px 0;font-size:26px}';
const fontLink='<link rel="stylesheet" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css">';
fs.writeFileSync(out+'/common/01-header-style.txt',fontLink+'\n<style>\n'+css+'\n'+fs.readFileSync('shop-assets/typography.css','utf8')+'\n</style>');
function main(file){return fs.readFileSync(file,'utf8').match(/<main>([\s\S]*?)<\/main>/)[1]}
function block(name,html,page='content'){html=html.replace(/src="shop-assets\/([^"]+)"/g,(m,f)=>'data-sr-image="'+f.replace(/\.(jpg|png)$/,'')+'" src="'+data.assetBase+f+'"').replace(/href="([^"?]+\.html)([^" ]*)"/g,(m,f,q)=>'data-sr-link="'+f+'" data-sr-query="'+q+'" href="'+(data.links[f]||'/')+q+'"');const code='<div class="sr-content" data-sr-block="'+name+'" data-page="'+page+'">\n'+html+'\n</div>';fs.writeFileSync(out+'/content/'+name+'.txt',code)}
const home=main('index.html');const sections=[...home.matchAll(/<section\b[^>]*>[\s\S]*?<\/section>/g)].map(m=>m[0]);
block('home-01-hero',home.slice(0,home.indexOf('<section')),'home');block('home-02-products',sections[0]);block('home-03-editorial',sections[1]);block('home-04-best',sections[2]);block('home-05-banner',home.slice(home.lastIndexOf('<div class="wrap"><div class="newsletter">')));
for(const page of ['shop','new','best','collection','about','shipping','terms','privacy'])block(page,main(page+'.html'),page);
const support=main('support.html').replace(/<div class="panel"><h2>문의 안내<\/h2>[\s\S]*?<\/div>/,'<div class="panel"><h2>문의하기</h2><p>상품·배송·교환 문의는 문의 페이지에서 접수해 주세요.</p><a class="button light" data-sr-contact href="/contact">문의하기 ↗</a></div>');block('support',support,'support');
block('contact-01-heading','<div class="wrap form-heading"><span class="eyebrow">CONTACT US</span><h2>무엇을 도와드릴까요?</h2><p>상품·배송·교환 관련 문의를 남겨 주세요.</p></div>','contact');block('contact-02-guide','<div class="wrap"><div class="panel"><h2>문의 전 확인해 주세요</h2><p>상품 문의는 상품명을, 주문 문의는 주문번호를 함께 적어 주세요.<br>응답 시간과 고객센터 연락처는 운영 정책에 맞게 입력해 주세요.</p></div></div>','contact');
const runtime=fs.readFileSync('imweb-runtime.js','utf8');fs.writeFileSync(out+'/common/03-footer-runtime.txt','<script>\n'+runtime+'\n</script>');
console.log('Shared CSS/settings/runtime + 16 content-only blocks generated');
