const fs=require('fs'),vm=require('vm'),assert=require('assert');
for(const file of fs.readdirSync('.').filter(x=>x.endsWith('.html'))){const t=fs.readFileSync(file,'utf8');for(const m of t.matchAll(/(?:href|src)="([^"]+)"/g)){const u=m[1].split('?')[0].split('#')[0];if(!u||u.startsWith('http')||u.startsWith('data:'))continue;assert(fs.existsSync(u),file+' -> '+u)}}
new vm.Script(fs.readFileSync('shop-assets/shop.js','utf8'));
for(const f of fs.readdirSync('imweb-handoff/content')){const t=fs.readFileSync('imweb-handoff/content/'+f,'utf8');assert(!/<(header|footer|script|style|form)\b/i.test(t),'Content contains infrastructure: '+f);assert(t.length<12000,'Large content block: '+f);assert(!t.includes('CONFIG'),'Per-page configuration: '+f)}
for(const f of fs.readdirSync('imweb-handoff/common'))for(const s of fs.readFileSync('imweb-handoff/common/'+f,'utf8').matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(s[1]);
const code=fs.readFileSync('imweb-runtime.js','utf8');assert(!/localStorage|\.onsubmit|document\.querySelector\(['"](?:header|footer|form)/.test(code));
function run(productUrls={}){const grid={dataset:{products:'all'},innerHTML:''};const anchor={dataset:{srLink:'shop.html',srQuery:'?category=tops'},href:''};const root={dataset:{page:'content'},querySelector:()=>null,querySelectorAll:s=>s==='[data-products]'?[grid]:s==='[data-sr-link]'?[anchor]:[],addEventListener:()=>{}};const doc={readyState:'complete',documentElement:{},querySelectorAll:()=>[root]};const data={assetBase:'https://example.com/assets/',links:{'shop.html':'/shopping?lang=ko'},productUrls,products:[{id:1,name:'<Unsafe & title>',price:10000,old:20000,tag:'BEST',image:'shirt',label:'TOP'}]};const context={window:{SR_SHOP:data},document:doc,location:{href:'https://example.com/page',search:''},URL,URLSearchParams,MutationObserver:class{observe(){}},requestAnimationFrame:fn=>fn()};vm.runInNewContext(code,context);return{grid,anchor,root,context}}
const unset=run();assert(unset.grid.innerHTML.includes('data-sr-unlinked'));assert(unset.grid.innerHTML.includes('&lt;Unsafe &amp; title&gt;'));assert(unset.anchor.href.includes('lang=ko'));assert(unset.anchor.href.includes('category=tops'));
const linked=run({1:'https://store.example.com/item/1'});assert(linked.grid.innerHTML.includes('https://store.example.com/item/1'));assert(!linked.grid.innerHTML.includes('data-sr-unlinked'));vm.runInNewContext(code,linked.context);
console.log('PASS: 16 content-only blocks, shared script syntax, escaped cards, native product routes, query preservation, idempotent bootstrap');
